pos(f(white, knight, square(6,4), square(4,5))).
neg(f(white, king, square(1,1), square(2,1))).
neg(f(white, king, square(1,1), square(2,2))).
neg(f(white, king, square(1,1), square(1,2))).
neg(f(white, knight, square(6,4), square(8,5))).
neg(f(white, knight, square(6,4), square(5,6))).
neg(f(white, knight, square(6,4), square(7,6))).
neg(f(white, knight, square(6,4), square(4,3))).
neg(f(white, knight, square(6,4), square(8,3))).
neg(f(white, knight, square(6,4), square(5,2))).
neg(f(white, knight, square(6,4), square(7,2))).